name: CI on pull request

on:
  pull_request:
    branches:
      - main
    paths:
      - 'react-frontend/**'
  workflow_dispatch:

jobs:
  Test-pipeline-execution:
    runs-on: ubuntu-latest
    steps:
      - run: echo "3rd Workflow"
      - name: checking the repo files
        run: ls ${{ github.workspace }}
