name: CI on pull request

on:
  pull_request:
    branches:
      - main
    paths:
      - 'react-frontend/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Workflow ran"
      - uses: actions/checkout@v3
      - run: ls -la 
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: cd react-frontend && npm install
      - run: cd react-frontend && npm run lint
      - run: cd react-frontend && npm run build
  
